# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "LingQuestionRequest" do
    optional :choice, :string, 1
  end
  add_message "LingQuestionResponse" do
    optional :question, :string, 1
  end
  add_message "LingAnswerRequest" do
    optional :answer, :string, 1
  end
  add_message "LingAnswerResponse" do
    optional :score, :string, 1
  end
end

LingQuestionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("LingQuestionRequest").msgclass
LingQuestionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("LingQuestionResponse").msgclass
LingAnswerRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("LingAnswerRequest").msgclass
LingAnswerResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("LingAnswerResponse").msgclass
